### ISSUE TITLE
能支持视频url地址输入吗？

### ISSUE THREAD

**Issue by tuzeao** [YaoFANGUK/video-subtitle-generator#11]
项目很棒，非常符合我的想法，就是如何支持视频url输入呢？
不是做这方面的，不太懂，大概告诉我思路就行

**Comment by YaoFANGUK** [comment]
emmm' 你改下源码就行了，加一个request，从url下载视频到本地 然后再识别

**Comment by tuzeao** [comment]
类似
`import requests
req = requests.get(MY_URL)
save_video(videopath)
SubtitleGenerator(video_path)
`
这样？有能直接读，不经过一道“存本地”的操作吗？比如类似图像是都转成base64的格式

**Comment by YaoFANGUK** [comment]
文件小的话可以直接读到内存里面啊

**Comment by tuzeao** [comment]
> 

ok
多谢，我试试
