### ISSUE TITLE
运行安装依赖报错

### ISSUE THREAD

**Issue by BozhiZhang-Shane** [YaoFANGUK/video-subtitle-generator#8]
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting audioread==2.1.9
  Using cached audioread-2.1.9.tar.gz (377 kB)
  Preparing metadata (setup.py) ... done
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi==1.15.0
  Using cached cffi-1.15.0.tar.gz (484 kB)
  Preparing metadata (setup.py) ... done
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting click==8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting decorator==5.1.1
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting filelock==3.6.0
  Using cached filelock-3.6.0-py3-none-any.whl (10.0 kB)
Collecting filesplit==3.0.2
  Using cached filesplit-3.0.2.tar.gz (5.7 kB)
  Preparing metadata (setup.py) ... done
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting joblib==1.1.0
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting librosa==0.9.1
  Using cached librosa-0.9.1-py3-none-any.whl (213 kB)
ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.38.0 Requires-Python >=3.7,<3.11; 0.38.1 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement llvmlite==0.38.0 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.33.0, 0.34.0, 0.35.0, 0.39.0, 0.39.1)
ERROR: No matching distribution found for llvmlite==0.38.0

前面运行的都很顺利，我也不知道这是怎么回事，希望大佬解答

**Comment by YaoFANGUK** [comment]
没有依赖llvmlite
